import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;

import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * Test suite for the Anagram class.
 * <p>
 * The provided test suite is correct and complete. You should not need to modify it. However, you
 * should understand it. You will need to augment or write test suites for later MPs.
 *
 * @see <a href="https://cs125.cs.illinois.edu/MP/2/">MP2 Documentation</a>
 */
public class AnagramTest {

    /**
     * Timeout for our tests. Solution takes 45 ms.
     */
    private static final int TEST_TIMEOUT = 500;

    /**
     * Test with precomputed values.
     */
    @Test(timeOut = TEST_TIMEOUT)
    public void testAreAnagrams() {
        for (Map.Entry<ArrayList<String>, Boolean> precomputed : PRECOMPUTED_RESULTS.entrySet()) {
            ArrayList<String> input = precomputed.getKey();
            Boolean output = precomputed.getValue();

            Assert.assertEquals(Anagram.areAnagrams(input.get(0), input.get(1)), (boolean) output,
                    "Incorrect result for " + input.get(0) + " and " + input.get(1));
        }
    }

    /**
     * Pre-computed testing values.
     */
    private static final Map<ArrayList<String>, Boolean> PRECOMPUTED_RESULTS =
            new LinkedHashMap<>() {
                {
                    put(new ArrayList<>() {
                        {
                            add(null);
                            add(null);
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add(null);
                            add("");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("");
                            add(null);
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("");
                            add("");
                        }
                    }, true);

                    put(new ArrayList<>() {
                        {
                            add("ABA");
                            add("aba");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("ABA");
                            add("a b a");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("Test me!");
                            add("Me, test.");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("Test me!");
                            add("Me, best.");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("Test test!");
                            add("Test.");
                        }
                    }, false);
                    /* BEGIN AUTOGENERATED CODE */
                    put(new ArrayList<>() {
                        {
                            add("LtDcAu3rQhP1W0hvkxpYk");
                            add("x0YhcAhpW,-,3Pt1vQ,L-r,kDuk");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("xpn6cvcXr6a7QwgaY7t5awdHaLpdpO6IsUvhWHvjmEaaP8q6FjiaZL8i");
                            add("5aaLOwXjdLH6vp6.w7tnd8r-haZIQg.FEc6-jPIp8imVvaaaYsWU7va.Hqx6!i");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("ef6G1KrAiXZmQynsS9Brv");
                            add("jXS9i61KNGAvnr381ZmeO");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("3YfmWiBqZ");
                            add("!VF,-q,iB,^f3Z,P");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("WmVVmxHjstC0cFrEVCAgN0k9sP601All2UiTdW");
                            add("Wr6AcmtWsViFPHj.lmr09klVU!AxCET^d00N.LCsV1");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("48n2IfSQGY");
                            add("Y2x,8 IG!hn^X,f");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("tmpNXe9aZfl0qZXT4tlYpc8HlgWebCQavBGT");
                            add("-BQaleTg4GZlNqXtcHtYpC0T!pbme9-!8lXaW^Zvf");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("4tcxs5fe9YRYZCMFM41mGvRxPGe1JIpHgPYWjW9O3eGOH8v");
                            add("ChZvPFeHIcGM.^OMDeCiW1WxgYzObef1YsmYJ99,t4RK-P8v,vx5");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("Y5HDaSkkDvOOsYVcCIyY8PLUfmOi8tcrGqrzCw9GbXE2KZxuOHR5MAH2FiB");
                            add("IUK^zsQcZGmACiw58Y5tYcv^OMFErDifYX2qSHB!uOrIa-G9WLCHV2k8ORPbDOy");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("d6rJcmwiY5azoJlrsecgX");
                            add("cw aJzYdm6oJrisgr5cleX");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("QLfik0UEraWGrNHUQpY9hjhRJZeme46jo");
                            add("rQoirk9paeje0jZfG6LUEmW-NQhY4HUhJR.");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("yl8ROkLEcNsY");
                            add(" k.lsYOyE -!LRc8^N");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("sdY7OLsjt8YO3ExHjUoXjFCo7StHNY7");
                            add("sCtU,!7xYj,8!7t7!jNOd.,YjHEs3HOXFYL^Soo");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("65SN7lR2cf3dTX75UwfFA");
                            add("3TA77FXRfd25UlS6Ncfw5");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("dH9urb7AXJIDGvPhTPyjeYhKsurSsgmTjhr5RMJ");
                            add("y9TKIm^X7Pg,8dRrr4SuPHJAC!ruY5-j.hsTsjGhJDM-b,");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("SF2Ro05mo9EH7SwzmX");
                            add("09m5SX-ooE2 SF7wR-zmH");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("H9ZLdpvYEPGOfmiB8HVkqFfCXXP6DOQZBQoYckz");
                            add("aD8^9aXGLBBCQvZPPVkqf6dYFXZcQoYpEOimkgzH");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("sgYuPzfPoDZ9h0FTQU6rsqbTeycAk");
                            add("sPfkqYT-Q!6uTh!F!AUZ^czegbsD  yr9Po0");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("65VrYZCPNXZA1JrJ8rMRFthQBnGkwRrmahwJ1yWhRPkcSMKEMnsOGszsBfgbD");
                            add("RMGJxBBZnbsGPrrMJ1QRaSK63y, zPw5WVgscZDNFOArh,XRkhFsRwtCmfMJY1w8");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("SS9nDezG5JQqZ79qCkScTEjSjC7i176");
                            add("ET^L7eS^FDvG!jzS9wZ7CC9r1qcL6kJS5n");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("vyY0aFttw1oFRDsD3dn63aYxBo8");
                            add("dto30aYvy^1DDR-wsoa3n!tB8xF6FY");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("BeGuO0dpU2RwvaR6ZwgKLWkfL0pWltNNjeTeo7ulnLuBouxN");
                            add("uZetxufa upk0,BjWN7KeG-LULl2BlR-6-n,go^TRNe0WvodLOwNpuw");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("suO07HOp22hrLQhT7X5xy1gN9EBEmavYkqPWeft");
                            add("ht,EPBEk5rf,Wpu7^QOv1X2YTesHmN0O279ygaqLx h");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("vGopGXYXqK7rc2nsdimgo0zj2XOytzGpQisVR");
                            add("iOVpidz-X2X^yzromQtYGnGcpqK2ss.XvG7Rq,yhj");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("UQ2BvMxhHfLcMrX4GFZ1EML10PwtYSrB7ajSOx9vG63Q11CHdXv89QlyGS6CWR");
                            add("GfvkGQwRctvPMxSlO691C,sQ11dF409xGYyhv28MHLBSEiLZ3B6XSaQi1CrTr7.M");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("hN6Mx1SpcvYzlkO66CpXkqKFOWokpfCASuskT");
                            add("SWk9opK,ftl ACNkCMqukhOckFp,Sx p-XvpsP6z6 1");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("bLwHE5bIU3qKA931QXgoYOd0VlGb73QVfd5m4RMUCsHPRMotka9370tVP3e");
                            add("3V7OQRRqQ ba VHV7YeK3td,tHILwM-mG5gbMXP!1E0Fo3U9doAsk9UEC5-VUl3P0");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("xpvlMQbCYwwmhyu2IYZ");
                            add("bX!-pCuGxhKyI24w,!MwWY.^-Z");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("AezCLDVR2ap7NNsFePSHPyl5pO55kucHS6PY6jOeQlMOg5Cvzw4P2dmwnBsRJIl");
                            add("MJHOP!7le!R62s0RwGg6p5ausw28PlzdVzmOnOBeIDl455SCFHDShNpP!,PNA5cLkMv");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("mmJqAGLTZnG5O27tK");
                            add("5!G!Amn q!tB7!T.OZLK.-G2m");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("5lLLNxu6YW9pxrWrFf");
                            add(" 5ELp Nl.,,,92FrYuxp rWx6^");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("cPKejHAJd1LqJEcP4a6G3RJpuI3WQmhTzGe45Qfrc0zOQE");
                            add("Ee6zQdKhPG,W3qGc45pQH^R-jQJPu,4c-aEIcLTA-rOJfm1 ze30J ");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("OJ95DPx26yEaHj3Zf8VmS7Stbu5sEFeTZTylnc");
                            add("6ZJcs,u ya7S Py.Z9mHT^eO8b5fDVjEF3,2ST,5tnElx!");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("lGAnXQniV8h0sXeg");
                            add("e^GgXn0nX8sV^Le Z^ ,!iU^");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("ISGCj8sO0klD6G2WmvcXSiT0ehp9pNu9Y0rgya16");
                            add("0 .g0haXG80pC1DG,6YSym!9jsIWce!2 lTvS6uN9rk!iOp");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("P8HU4cHNYXnLPBlfZqpvzKHDgzgvKBYDcd68gDgmeKWSEUxfU");
                            add("Nn!qPvBY8zP8vgBXgx4HUccWgKzUfLS.mDH-EegpZKDYD6d Hf,KUl");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("U2INgIGouDH30JEnRbWUFWxWlWsJpzJ66OETGp6h6hCgt27CarmxftU4m0WEnvN1");
                            add("Wt!EozOGUh1S6JqEWs62CG7n60JFIWxtSWeD02uHmbTlNnpr3fsUpmvxENg,C,6gmUW");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("yprCAImsUf82hXj7EGpURHj7E0VYGJ9sCSYYjdwPbmK");
                            add("2GY9UXn28IEAPEyUHJ0S7bCpprA!7djTwYftVsjCRjmY");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("CDJiXF3pRZnWVSS3M");
                            add("CRJ3ZaSFWSrnpMjVD");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("wZYuegVLcTFatfosesaymMfHJ5J2UjFVyRyG7bnz6WXSmxVEYFeifG21A");
                            add(".Js9LVs2gXmRZcf^mVfoiH!za7FTy!AYtm57eG16VbunFx2Ms- wfyj,GyUa!ehJe");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("CwDgWl9by7H45bMMG8WT6i");
                            add("WTCwm75H a1MHbbGiDM9yW3");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("3YecA5zvOPsZIygqRBV78zoPgEOHFLMdF8EEnBXZ5wBT2CV3ccV9Kt");
                            add("-OcFzE3X9zP,Zq2gZLVBETCK3syw8c5OIAB-^8FEgce7VstRYvn65HTVBd");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("htnZLlwTyWeWxpPBbF5CEQXtDK8p4zXGxPWhv");
                            add("hWnEpWh8tTPtXDxeFByXPKLbQwWp,GlzZv45Cx");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("ExCbCnYhrTDKLYB");
                            add("hCLYBxTY^C^K.b^--DrnE");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("XkXwVIcfzBanG");
                            add("afags7cnkXz-EX");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("fWyS0KWbcRNufb2IcaCh7tRR7");
                            add("S^aWyRKCR7c2h7NfIbfbR.cuWt0");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("xhcCGd9JhzEUsrZ38WqxPhHumEvVyy1LJO8zw8WFD");
                            add("h78scPyJyrNErW79,VXUGHhz8WO Z8ChvqFJwDx3En1");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("kXCEoweWqXFX4yKa73RVjrio1jnCdaxPBf8W5JuS");
                            add("a5qdnaFojS8xR4jvw uB7W iW,y1XCE3fHVJXPCoK,o !O");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("tlMYcplUi7e9");
                            add(" .li!tcl.M,U Yp!79e");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("9jksXLLTjtAzKeeJvXRGNKJFIrnRBOpjNEPW9kxdXW1RwH9w2IGYTnvrBo6");
                            add("kBre1!GLvESW.F9HJsO9IBjXNLRKAZG8wRePFN9xLvXw^on-PkzbT2jnJ.^TdtXIW");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("LMNCT1YfqoeNtmN4NBiMX4AS6ZrCypLQaeb5HV7e2e4CohsdEcEncPqO9MaRM");
                            add("ZPbMC464NAQf.!as2,OtS-ye-qdeQ5!eVo4cERqMNTEeciHX7r7h9nNm.RL1Be1YMaoC");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("gnfkp83JDOygXxIj");
                            add("gIOxnXJky^g-Dp8fj3");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("PoXNMTVhDveNDDtH05QzihCGK6VpaQjhtDfYgxatBkur7LZc");
                            add("Hzt7QMBKxG6ZhgiDVo-jeN!t0kahQDcXptrNDVaCfPDLTY5huv");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("2oZB23wjktYAtkoghZ2IEE71Zd7QIgDmgky8I");
                            add("wZIZwoA7,YgtQ27jdEA1722m EZ!IZkfwItk!g2B,o");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("whb1cuCPVll9xzKd0Nhn1KlKO5");
                            add("1dcwhb0Cu^,OKnlKlKP5x,h9VNl^z1");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("7OJH1DG49DjLyFEyfunFtCmTqSbo74cHBMeb8qb50L7rxVDTMHsb8RO0smN2AG5");
                            add("5Gu4B5CO8bfc7y7G2TELLSjJDN49b0D1TqsoHnF- 0DVqH8mHMFb7ROr!exbm tMAys");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("BVMqXoQViYh4zvFUytgz0C9amPNQnE2mqZnFX4jv6iF8R4sMLQeBGYRA4LTKX");
                            add("gaRtvFAzL9eVRQXXqiTy8v6G U,zoVNFLXnihBmjM^YMKnsEFPq4BYCZmQ4420,Q4");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("EM3pPD1hAAwy8jNVdjkQ4iILn");
                            add("A,INM1d3jn8V!jyhEQp-4..LDiPkwA");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("iDLxcflWM86R4VQwPxNA0NnUXexy1F9Nq5XT2AqYK74FKYdPTGtGMapGNtubzD4");
                            add("tzxTDPtNLiKGAFMYd26NNYV wXRTU 5QnXp44bc1K4ue7xqAqD8GaF90xPfGMWylN");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("M4U6CKxEUkppFcD49fKyRPWYpreS8f6biclOSjKP1lAUEqWTbOy9Yc");
                            add("9Yyb4pPAxcOY-EK1US69PyTpOCR6UFekK MWDf4jKlcUb8iqfrlcSEWp");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("wJB0Vik9GHknZV4VU6fXLZSr3ijrk888");
                            add("r -BVfi4U3kj Z8d90JVH k8 7kH6wSiG!xMLX");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("IGqzOHYB5gH");
                            add("BkaH,3gYHGBO");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("bqR6EWohyleNICabYeSCySL0lQsSSIWJkdVMtgvV0K92StoRGNTPxBYwmAH6Ki");
                            add("BHexE6de9ANoha0tCMSJSNRtoSlilYVbqbyW6KGYsSIVyQWvKCT0gSmPwIR2kL");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("xrtYeJivZ315u");
                            add("XerZx!,-,Z,5C1^2.SvY");
                        }
                    }, false);
                    /* END AUTOGENERATED CODE */
                }
            };
}
